### ISSUE TITLE
Cannot unmarshal silencesData

### ISSUE THREAD

**Issue by robsonpeixoto** [cloudflare/unsee#26] opened 2017-03-30 12:49 UTC
```
INFO[0360] GET http://monitoring-1:9093/api/v1/silences?limit=4294967295
ERRO[0360] json: cannot unmarshal array into Go struct field SilenceAPIResponse.data of type alertmanager.silencesData
```

**Comment by Tenzer** [comment] 2017-03-30 14:44
This is a duplicate of #24. There's work on a fix in #23. It's because we (Cloudflare) haven't yet upgraded to Alertmanager 0.5.x and the API response has changed in between 0.4 and 0.5.

**Closed by Tenzer** 2017-03-30 14:44 UTC
